##### Individual-Level SSF #####

library(amt)
library(tidyverse)
library(sjPlot)
library(terra)
library(sf)
library(tictoc)
library(parallel)

set.seed(1)

##### 1a. Prepare Data #####

# read data
#movdata <- readRDS('./SSF/eledata_expanded.rds')
movdata <- readRDS('./SSF/eledata_allmara.RDS')
movdata <- movdata[!movdata$subject_name %in% c('Shamba','Courtney','David','Pepper'),]

# create date object
movdata$date <- as.POSIXct(movdata$date) # check still in EAT

# add new variable for individual-year (name-year) that can be used to group and fit models by. Years use april cutoff
movdata$subject_year <- paste(movdata$subject_name, movdata$year.cuts, sep = '-')

# make a move object for the amt package - we will use the id, which is a
#         combination of the animal's name and collar number
track <- make_track(movdata, .x = x, .y = y, .t = date, id = id, subject_name = subject_name)
t1 <- split(track, track$id)

# create bursts and traj - map the two functions to a nested dataset t1
t2 <- lapply(t1, function(x)
  x %>% track_resample(rate = minutes(60), tolerance = minutes(30)) %>% steps_by_burst() %>%
    mutate(id = unique(x$id)))

## plot the step length and turning angle distributions

# Plot step length and turn angle distributions
p <- do.call(rbind, t2)
ggplot(p, aes(sl_, fill = factor(id))) + geom_density(alpha = 0.4)
ggplot(p, aes(ta_, fill = factor(id))) + geom_density(alpha = 0.4)


##### Generate SSF Availability sample #####
#' Next we will generate the availability sample for the Step Selection and integrated Step Selection functions. 
#' Here, the availability sample is generated by drawing random steps that the animal could have taken from each recorded
#' location. We draw 5 steps per used location, and  assume a gamma step length distribution and von Mises 
#' turning angle distribution. 

## make random steps for SSF and iSSF

avail.steps = 10
# get pop-level step length and turn angle distributions
p <- do.call(rbind, t2)
sl_distr = fit_distr(p$sl_, "gamma")
ta_distr = fit_distr(p$ta_, "vonmises")

# create random steps
{tic()
  cores = 6
  ssf.randsteps <- parallel::mclapply(t2, function(x) {
    set.seed(1)
    x %>% random_steps(n_control = avail.steps, 
                      sl_distr = sl_distr,
                      ta_distr = ta_distr) }, mc.cores = cores)
toc()}

# create dataframe
ssf.randsteps <- do.call(rbind, ssf.randsteps)
# check
head(ssf.randsteps)

# add subject_names
t <- movdata %>% group_by(id, subject_name, subject_sex, tactic.agg) %>% tally() %>% dplyr::select(-n)
ssf.df <- inner_join(x = t, y = ssf.randsteps, by = 'id')

# look at turning angle distribution for random steps
ssf.df %>% 
  #tidyr::unnest(col = steps) %>% # only needed if rand steps are by indv.
  filter(case_ == FALSE) %>%
  ggplot(aes(ta_, fill = factor(subject_name))) + geom_density(alpha = 0.4)

# look at step length distribution for random steps
ssf.df %>% 
  #tidyr::unnest(col = steps) %>% # only needed if rand steps are by indv.
  filter(case_ == FALSE) %>%
  ggplot(aes(sl_, fill = factor(subject_name))) + geom_density(alpha = 0.4)


# remove extra dataframes
remove(ssf.randsteps)


##### Covariate Extraction #####

#' We now have used (case_ == TRUE) and available (case_ == FALSE) points for each individual. Before we can begin 
#' modeling, we have to extract covariates. We will use the amt package function to do this. 

# import layers - note that to use the amt functions they need to be raster objects, not terra objects
library(terra)
# import layers
prop.ag <- rast("./spatial data/Estes_ag_pct_1500.tif")	
prop.forest <- rast("./spatial data/hansen_forest_pct_250.tif")		
slope <- rast('./spatial data/slope_estes_32736_2020-05-12.tif')
ndviCoV <- rast('./spatial data/NDVICoV_estes_32736-2022-02-03.tif')
prop.settlement.250 <- rast("spatial data/estes_settlement_pct_250.tif")
prop.settlement.1500 <- rast("spatial data/estes_settlement_pct_1500.tif")
gHM <- rast("./spatial data/gHM_estes_32736_2020-05-12.tif")

# tiedman layer
# 1 = ag
# 2 = cover20
# 3 = cover2070
# 4 = cover70
# 5 = degraded
lc <- rast("./spatial data/Tiedman/agmask_reclass.tif")
ag <- terra::clamp(lc, lower = 1, upper = 1, values = FALSE)
cover20 <- terra::clamp(lc, lower = 2, upper = 2, values = FALSE)
cover2070 <- terra::clamp(lc, lower = 3, upper = 3, values = FALSE)
cover70 <- terra::clamp(lc, lower = 4, upper = 4, values = FALSE)

#drains
# get shapefile for drains buffer
drains <- st_read("./spatial data/drains/drains_estes_20211117/drains_estes_-2021-11-17.shp", 
                  layer="drains_estes_-2021-11-17", crs = 4326) %>%
  st_transform(crs = 32736) %>%
  filter(RIV_ORD <= 7)
# buffer by 250m
drains <- st_buffer(drains, dist = 250) %>%
  st_union() %>%
  terra::vect() %>%
  terra::rasterize(.,ag) # rasterize at 10m sentinel 


## Create covariate list
# rasters must be in a list for mcapply
r.list <- list(slope, ndviCoV, ag, cover20, cover2070, cover70, drains, prop.settlement.250, prop.settlement.1500, gHM)

## Extract

# create terra vect object
study.area <- 32736
ssf.sf <- ssf.df %>%
  st_as_sf(coords = c('x2_','y2_'), crs = study.area) %>% # specify here to extract at beginning (x1/y1) or end (x2/y2) of step
  terra::vect() 

# extract in parallel - xx seconds with allmara dataset
{tic()
  cores = 6
  extract <- mclapply(r.list, function(x)
    terra::extract(x, ssf.sf)[,2], mc.cores = cores)
  used <- do.call(cbind, extract) # bind results into an extracted dataframe
  toc()}

# check
head(used)
summary(used)

# create data frame
mode(used) = "numeric"
used <- as.data.frame(used)
colnames(used) <- c('slope','ndviCoV','ag','cover20','cover2070','cover70','drains','prop.settlement.250','prop.settlement.1500','gHM')
head(used)

# unstandardized data frame
ssf.ext <- cbind(ssf.df, used)

# scale some covariates before we fit it
ssf.ext <- ssf.ext %>%
  mutate_at(.vars = c('slope', 'ndviCoV'), .funs = scale) %>%
  mutate_at(.vars = c('ag','cover20','cover2070','cover70','drains'), .funs = function(x) if_else(!is.na(x), 1, 0)) %>%
  mutate_at(.vars = c('ag','cover20','cover2070','cover70', 'drains'), .funs = as.factor) %>%
  # create covariates for the cosine of the turning angle and log step length. We will compare step length and log step length in the model
  mutate(cos_ta_ = cos(ta_),
         log_sl_ = log(sl_ + .001)) # add a small value for steps of length 0


# filter out NDVI cov outliers
ssf.ext <- ssf.ext[ssf.ext$ndviCoV < 20,] # removes three major outliers from Marima dataset

#' Our covariates are now extracted. Before model fitting, check the data frame to make sure we did everything 
#' correctly!

summary(ssf.ext)

# drop old dataframes
remove(extract)
remove(used)


##### Fit SSF Model #####
#TODO: Add model selection code


# m.ssf <- ssf.ext %>% amt::fit_clogit(case_ ~ ag + cover20 + cover2070 + cover70 + slope + ndviCoV +
#                                      sl_ + log_sl_ + cos_ta_ + # movement parameters
#                                      strata(step_id_))
# 
# m.ssf <- survival::clogit(case_ ~ ag + cover20 + cover2070 + cover70 + slope + ndviCoV +
#                             sl_ + log_sl_ + cos_ta_ + strata(step_id_),
#                           data = ssf.ext)
# 
# summary(m.ssf)



##### Fit Individual SSFs #####

# # test code
# t <- amt::fit_issf(m.ind.ssf[[1]], case_ ~ ag + cover20 + cover2070 + cover70 + slope + ndviCoV +
#                 sl_ + log_sl_ + cos_ta_ + # movement parameters
#                 strata(step_id_))
# 
# survival::clogit(case_ ~ ag + cover20 + cover2070 + cover70 + slope + ndviCoV +  
#                    sl_ + log_sl_ + cos_ta_ + strata(step_id_), data = m.ind.ssf[[1]])

## Run in parallel 

# fit model
library(survival)
{tic()
  cores = 6
  m.ind.ssf <- split(ssf.ext, ssf.ext$subject_name) # chose splitting variable (subject_name or subject_year)
  m.ind.ssf <- mclapply(m.ind.ssf, function(x) {
    t <- amt::fit_issf(x, case_ ~ ag + cover20 + cover2070 + cover70 + slope + ndviCoV +
                          sl_ + log_sl_ + cos_ta_ + # movement parameters
                          strata(step_id_)) 
    t <- t$model }, # select only the model output
    mc.cores = cores)
  names(m.ind.ssf) <- unique(ssf.ext$subject_name)
toc()}


# get table of estimates for each individual
id.est.ssf <- lapply(m.ind.ssf, function(x) 
  tab <- x %>% broom::tidy() %>%
    mutate(
      ymin = estimate - 1.96 * std.error,
      ymax = estimate + 1.96 * std.error
    ))
id.est.ssf <- dplyr::bind_rows(id.est.ssf, .id = "subject_name")

# add other ele metadata (sex, ag tactic, etc.)
t <- movdata %>% group_by(subject_name, subject_sex, tactic.agg) %>% tally() %>% dplyr::select(-n)
id.est.ssf <- merge(id.est.ssf, t, by = 'subject_name')


##### plot results #####

# coeff estimates for all individuals
ggplot(id.est.ssf, aes(x = as.factor(term), y = estimate, color = subject_name)) + 
  geom_pointrange(aes(ymin = ymin, ymax = ymax),
                  position = position_dodge(width = 0.3)) +
  xlab('covariate') + ggtitle('rsf individual-level estimates') +
  labs(color = 'subject_name') + 
  coord_flip()

# coeff estimates by sex
ggplot(id.est.ssf, aes(x = as.factor(term), y = estimate, color = subject_sex)) +
  geom_boxplot() +
  xlab('covariate') + ggtitle('rsf individual-level estimates by sex') +
  labs(color = 'sex') + 
  coord_flip()

# coeff estimates by tactic (aggregate)
ggplot(id.est.ssf, aes(x = as.factor(term), y = estimate, color = factor(tactic.agg))) +
  geom_boxplot() +
  xlab('covariate') + ggtitle('rsf individual-level estimates by ag tactic') +
  labs(color = 'ag tactic (aggregate)') + 
  coord_flip() 
